name: CI
on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14
          - 16
          - 18
          - 20
    runs-on: '${{ matrix.os }}'
    name: Testing on ${{ matrix.os }} with node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v4
    
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '${{ matrix.node }}'
        
    - name: Install dependencies
      run: npm install 
      
    - name: "Run Tests"
      run: npm run test


