name: CI
on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16
          - 18
          - 20
    runs-on: '${{ matrix.os }}'
    name: Testing on ${{ matrix.os }} with node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '${{ matrix.node }}'
        
    - name: Install Dependencies
      run: npm install 
      
    - name: Run Tests
      run: npm run test

  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.${{ github.run_number }}.${{ github.run_attempt }}
      NODE_ENV: production

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install 
      
    - name: Build
      run: npm run build

    - name: Package
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        npm version --no-git-tag-version ${{ env.VERSION }}
        npm pack

    - name: Tag Release
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        token: ${{ secrets.RELEASE_TOKEN }}
        files: |
          *.tgz