name: CI
on:
  push:
    branches:
      - '**'
runs-on: ubuntu-latest

jobs:
  test:
    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install 
    - name: "Run Test"
      run: npm run test


